---
apiVersion: v1
kind: Service
metadata:
  name: piazza-api
spec:
  type: LoadBalancer
  selector:
    app: piazza-api
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-api
  labels:
    app: piazza-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: piazza-api
  template:
    metadata:
      labels:
        app: piazza-api
    spec:
      containers:
      - name: piazza-api
        image:  sever3d/piazza-api:latest
        imagePullPolicy: Always
        env:
        - name: MURL
          value: mongodb+srv://MONGO_USER:MONGO_PASSWORD@MONGO_CLUSTER/MONGO_COLLECTION?retryWrites=true&w=majority
        - name: TOKEN_SECRET
          value: TOKEN_SECRET_STRING
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "500m"
      restartPolicy: Always

