---
apiVersion: v1
kind: Service
metadata:
  name: piazza-api
spec:
  type: LoadBalancer
  selector:
    app: piazza-api
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-api
  labels:
    app: piazza-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piazza-api
  template:
    metadata:
      labels:
        app: piazza-api
    spec:
      containers:
      - name: piazza-api
        image:  us-east1-docker.pkg.dev/GOOGLE_PROJECT_ID/piazza-api/piazza-api:latest
        imagePullPolicy: Always
        env:
        - name: MURL
          value: MONGO_CONN_STRING
        - name: TOKEN_SECRET
          value: TOKEN_SECRET_STRING
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "600Mi"
            cpu: "500m"
      restartPolicy: Always

