---
apiVersion: v1
kind: Service
metadata:
  name: piazza-api
spec:
  type: LoadBalancer
  selector:
    app: piazza-api
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-api
  labels:
    app: piazza-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piazza-api
  template:
    metadata:
      labels:
        app: piazza-api
    spec:
      containers:
      - name: piazza-api
        image:  us-east1-docker.pkg.dev/GOOGLE_PROJECT_ID/piazza-api/piazza-api:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "600Mi"
            cpu: "500m"
      restartPolicy: Always

