name: Publish DockerHub deploy GCP K8S

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: sever3d/piazza-api
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
      - name: Install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Deploy to GKE
        env: 
            GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
            MONGO_USER: ${{ secrets.MONGO_USER }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
            MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
            MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
            TOKEN_SECRET_STRING: ${{ secrets.JWT_TOKEN_SECRET }}
        run: |
            gcloud container clusters get-credentials cloud-computing-cluster --region us-central1
            sed -i "s/GOOGLE_PROJECT_ID/$GOOGLE_PROJECT_ID/g" resources.yml
            sed -i "s/TOKEN_SECRET_STRING/$TOKEN_SECRET_STRING/g" resources.yml
            sed -i "s/MONGO_USER/$MONGO_USER/g" resources.yml
            sed -i "s/MONGO_PASSWORD/$MONGO_PASSWORD/g" resources.yml
            sed -i "s/MONGO_CLUSTER/$MONGO_CLUSTER/g" resources.yml
            sed -i "s/MONGO_COLLECTION/$MONGO_COLLECTION/g" resources.yml
            kubectl apply -f resources.yml