name: 'SemVer Tag and Docker Build and Push'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-tag-docker.yml@v2
    with:
      image: 'sever3d/piazza-api'
    secrets: inherit